services:
  prometheus:
    image: prom/prometheus:v2.43.0
    ports:
      - "9090:9090"
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
    links:
      - app
      - victoria-metrics
    entrypoint:
      - "/bin/prometheus"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    
  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.93.11
    ports:
      - "8428:8428"

  grafana:
    image: grafana/grafana-oss:9.5.6
    ports:
      - "3000:3000"
    volumes:
      - "./config/grafana/new/grafana.ini:/etc/grafana/grafana.ini"
      # init data sources
      - "./config/grafana/new/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/grafana-datasource.yaml"
      # init dashboards loader
      - "./config/grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboard.yaml"
      # dashboards
      - "./config/grafana/dashboards:/var/lib/grafana/dashboards"
      - "./config/grafana/plugins:/var/lib/grafana/plugins"
    links:
      - prometheus
      - victoria-metrics

  grafana-legacy:
    image: grafana/grafana-oss:8.4.4
    ports:
      - "3001:3000"
    volumes:
      - "./config/grafana/legacy/grafana.ini:/etc/grafana/grafana.ini"
      # init data sources
      - "./config/grafana/legacy/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/grafana-datasource.yaml"
      # init dashboards loader
      - "./config/grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboard.yaml"
      # dashboards
      - "./config/grafana/dashboards:/var/lib/grafana/dashboards"
    links:
      - prometheus
      - victoria-metrics

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./src/main.py:/app/main.py"
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --reload
