services:
  prometheus:
    image: prom/prometheus:v2.43.0
    ports:
      - "9090:9090"
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
    links:
      - app
    entrypoint:
      - "/bin/prometheus"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"

  grafana:
    image: grafana/grafana-oss:8.4.4
    ports:
      - "3000:3000"
    volumes:
      - "./config/grafana.ini:/etc/grafana/grafana.ini"
    links:
      - prometheus

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./src/main.py:/app/main.py"
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --reload
