apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: VictoriaMetrics
    type: victoriametrics-datasource
    uid: P4169E866C3094E38
    access: proxy
    url: http://victoria-metrics:8428
    isDefault: false
